In [18]:
pip install pandas

In [27]:
import numpy as np
import pandas as pd

In [28]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
np.arange(0,20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
data=pd.DataFrame(np.arange(0,20).reshape(4,5),index=['R1','R2','R3','R4'],columns=['C1','C2','C3','C4','C5'])

In [23]:
print(data)

    C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19


In [24]:
data.loc['R1']

C1    0
C2    1
C3    2
C4    3
C5    4
Name: R1, dtype: int32

In [25]:
data.loc['R2']

C1    5
C2    6
C3    7
C4    8
C5    9
Name: R2, dtype: int32

In [26]:
data.iloc[:,:]

C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19

In [31]:
data.iloc[:3,:3]

C1  C2  C3
R1   0   1   2
R2   5   6   7
R3  10  11  12

In [32]:
data.iloc[:,:]

C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19

In [34]:
data.iloc[1:,1:4]

C2  C3  C4
R2   6   7   8
R3  11  12  13
R4  16  17  18

In [35]:
data.iloc[:,:]

C1  C2  C3  C4  C5
R1   0   1   2   3   4
R2   5   6   7   8   9
R3  10  11  12  13  14
R4  15  16  17  18  19

In [36]:
data.iloc[:,:].values

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [41]:
np.array(data)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])